

url: "the_sites_url_here.com"
plugins:
  - jekyll-sitemap
    
_select_data:
  aspect-ratios:
    - portrait-tall
    - portrait
    - square
    - landscape
    - landscape-wide
  column-sizes:
    col-6: One-Half
    col-12: Full Width
    col-4: One-Third
    col-3: One-Quarter
    col-6_sm-12: One-Half (Stacked)
    col-4_sm-12: One-Third (Stacked)
    col-3_sm-12: One-Quarter (Stacked)

_comments:
  title: Max 70 characters
  social_image: Landscape 1200 x 600px
  twitter_card: summary, photo, video, product, app, gallery
  twitter_description: 200 characters
 
